name: chetam brat
on:
  push:
    branches: [ "main" ]  # Trigger on push to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # name: "Build and Test"
    # runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   pull-requests: write

    # steps:
    # - uses: actions/checkout@v3
    # - name: Use Node.js 16.x
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: 16.x
    #     cache: npm
    # - run: npm ci
    # - run: npm run build --if-present
    # - run: npm test
    # - name: Report Coverage
    #   uses: davelosert/vitest-coverage-report-action@v2
    #   if: always()

  
  package-and-publish:
    needs:
      - build

    name: 🐳 Package & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step to log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Use your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}    # Use your Docker Hub token

      - name: Generate Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/zangar-chetamski-chetam  # Replace with your Docker Hub repository name
          tags: |
            type=ref,event=tag
            type=ref,event=pr
            type=sha,event=branch,prefix=,suffix=,format=short

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/zangar-chetamski-chetam:latest  # Replace with your Docker Hub repository name
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs:
      - package-and-publish  # Ensure CD only runs after CI and packaging are done
    runs-on: self-hosted  # This will use your self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Pull Docker Image
        run: |
          # Pull the latest image from Docker Hub
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/zangar-chetamski-chetam:latest
  
      - name: Deploy Docker Container
        run: |
          # Gracefully stop and remove the old container if exists
          sudo docker stop my-container || true
          sudo docker rm my-container || true
          
          # Run the new container
          sudo docker run -d --name my-container -p 80:5000 ${{ secrets.DOCKER_USERNAME }}/zangar-chetamski-chetam:latest
  
          # Clean up unused Docker resources
          sudo docker system prune -f
